packages_list:
  - 'binutils'
  - 'compat-libcap1'
  - 'compat-libstdc++-33.x86_64'
  - 'gcc.x86_64'
  - 'gcc-c++.x86_64'
  - 'glibc.x86_64'
  - 'glibc-devel.x86_64'
  - 'libaio.x86_64'
  - 'libaio-devel.x86_64'
  - 'libgcc.x86_64'
  - 'libstdc++.x86_64'
  - 'libstdc++-devel.x86_64'
  - 'ksh'
  - 'make'
  - 'sysstat'

kernel_params:
        kernel.shmmax: 4294967295
        kernel.sem: 25632000100142
        kernel.shmall: 524288
        net.core.rmem_max: 16777216
        net.core.wmem_max: 16777216
        net.ipv4.tcp_rmem: 4096 87380 16777216
        net.ipv4.tcp_wmem: 4096 65536 16777216
        vm.swappiness: 10
        vm.dirty_background_ratio: 5
        vm.dirty_ratio: 10
        fs.file-max: 262144
        net.ipv4.tcp_keepalive_time: 300
        net.ipv4.tcp_keepalive_intvl: 60
        net.ipv4.tcp_keepalive_probes: 10
        net.ipv6.conf.all.disable_ipv6: 1

soft_no_file: 4096
hard_no_file: 65536
soft_nproc: 2047
hard_nproc: 16384

oracle_groups:
    - { group: oinstall, gid: 54321 }
    - { group: dba, gid: 54322 }


oracle_users:         # Passwd :oracle
    - { username: oracle, uid: 54321, primgroup: oinstall, othergroups: "dba", passwd: "$6$VwR.53R4$HtKoSj3TxZCc4nWoqCrnBx8ldjJ2e7pfe1KKEvjkctAK653RL5FfsPRh5SuhrZEcGElba.G68EPHG3dV5z7ty." }

admin_server_port: 7001
wsm_server_port: 7010
soa_server_port: 8001
osb_server_port: 8011
ess_server_port: 7011
nodemanager_port: 5556

domain_name: testdomain
oracle_base: /u01/oracle
shared_config_dir: '{{ oracle_base }}/config'
products_dir:  '{{ oracle_base }}/products'
runtime_dir: '{{ oracle_base }}/runtime'
oracle_home: '{{ products_dir }}/fmw'
oracle_common_home: '{{ oracle_home }}/oracle_common'
wl_home: '{{ oracle_home }}/wlserver'
java_home: '{{ products_dir }}/jdk'
local_oracle_base: /u02/oracle
software_location: '{{ oracle_base }}/installation_packages'
domain_name: testdomain
domains_location: '{{ shared_config_dir }}/domains'
applications_location: '{{ shared_config_dir }}/applications'
aserver_home: '{{ domains_location }}/{{ domain_name }}'
application_home: '{{ applications_location }}/{{ domain_name }}'
nm_home: '{{ local_oracle_base }}/config/nodemanager'
mserver_home: '{{local_oracle_base}}/config/domains/{{ domain_name }}'
wlscripts: '{{ oracle_base }}/wlscripts'
jms_store_location: '{{ oracle_base }}/runtime/{{ domain_name }}'
